/* Portfolio UI-kit content. Sets window.TS_DATA. Galeriler asset klasörlerinden otomatik tamamlandı. */
window.TS_DATA = {
  "webmReady": false,
  "works": [
    {
      "id": "limo",
      "cat": "reklam",
      "video": true,
      "videoSrc": "limo-ltx.mp4",
      "image": "assets/work/limo-poster.webp",
      "meta": "Reklam · LTX 2.3 · 25fps",
      "title": "Sokak Köpeği Limo",
      "desc": "Barınaktan kurtarıldı."
    },
    {
      "id": "benzin",
      "cat": "reklam",
      "video": true,
      "videoSrc": "showreel.mp4",
      "image": "assets/work/javier.webp",
      "fit": "scale-down",
      "meta": "Klip · LTX 2.3 · 24fps",
      "title": "Benzin İstasyonu — Animasyon Kısa Film",
      "desc": "İki karakterli, kilitli kamera sinematik kısa. Karakter tasarımından lip-sync'e tam pipeline."
    },
    {
      "id": "kidrobot",
      "cat": "reklam",
      "video": true,
      "videoSrc": "dog.mp4",
      "image": "assets/work/dog-poster.webp",
      "fit": "contain",
      "meta": "Reklam · LTX 2.3 · 24fps",
      "title": "Dog — Karakter Reklamı",
      "desc": "Köpek karakterli kısa reklam filmi. Lip-sync ve animasyon tam pipeline."
    },
    {
      "id": "donald",
      "cat": "reklam",
      "video": true,
      "videoSrc": "bunnyskate.mp4",
      "image": "assets/work/bunnyskate-poster.webp",
      "meta": "Reklam · LTX 2.3 · 24fps",
      "title": "BunnySkate — Reklam Filmi",
      "desc": "Kaykaylı karakter reklam filmi. Hareket ve sahne ışığı uçtan uca AI pipeline ile."
    },
    {
      "id": "keyblade",
      "cat": "reklam",
      "video": true,
      "videoSrc": "nesquik.mp4",
      "image": "assets/work/nesquik-poster.webp",
      "fit": "contain",
      "meta": "Reklam · LTX 2.3 · 24fps",
      "title": "Nesquik — Ürün Reklamı",
      "desc": "Marka ürün reklamı için sinematik kısa. Karakter ve ürün kurgusu tek elden."
    },
    {
      "id": "toys",
      "cat": "reklam",
      "video": true,
      "videoSrc": "toys.mp4",
      "image": "assets/work/toys-poster.webp",
      "meta": "Reklam · LTX 2.3 · 24fps",
      "title": "ToyS — Koleksiyon Figür Reklamı",
      "desc": "Premium koleksiyon figürü için sinematik ürün filmi. Sahne ışığı ve materyal çalışması AI pipeline ile."
    },
    {
      "id": "park-problem",
      "cat": "reklam",
      "video": true,
      "videoSrc": "park problem.mp4",
      "image": "assets/work/park-problem-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "Park Problem",
      "desc": "AI karakter geliştirme ve animasyon. Konseptten render'a uçtan uca lokal pipeline."
    },
    {
      "id": "doc-comodoturtle",
      "cat": "reklam",
      "video": true,
      "videoSrc": "doc comodoturtle.mp4",
      "image": "assets/work/doc-comodoturtle-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "Doc — Komodo Turtle",
      "desc": "AI karakter geliştirme ve animasyon. Karakter tasarımı ve hareket tek elden."
    },
    {
      "id": "dino",
      "cat": "reklam",
      "video": true,
      "videoSrc": "dino.mp4",
      "image": "assets/work/dino-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "Dino",
      "desc": "AI karakter geliştirme ve animasyon. Konseptten render'a uçtan uca lokal pipeline."
    },
    {
      "id": "crab",
      "cat": "reklam",
      "video": true,
      "videoSrc": "crab.mp4",
      "image": "assets/work/crab-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "Crab",
      "desc": "AI karakter geliştirme ve animasyon. Karakter tasarımı ve hareket tek elden."
    },
    {
      "id": "mission-mars",
      "cat": "reklam",
      "video": true,
      "videoSrc": "mission mars.mp4",
      "image": "assets/work/mission-mars-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "Mission Mars",
      "desc": "AI karakter geliştirme ve animasyon. Konseptten render'a uçtan uca lokal pipeline."
    },
    {
      "id": "soldier",
      "cat": "reklam",
      "video": true,
      "videoSrc": "soldier.mp4",
      "image": "assets/work/soldier-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "Soldier",
      "desc": "AI karakter geliştirme ve animasyon. Karakter tasarımı ve hareket tek elden."
    },
    {
      "id": "2funart-mice",
      "cat": "reklam",
      "video": true,
      "videoSrc": "2funart-mice.mp4",
      "image": "assets/work/2funart-mice-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "Kitchen Mouse",
      "desc": "AI karakter geliştirme ve animasyon. Konseptten render'a uçtan uca lokal pipeline."
    },
    {
      "id": "2funart-video13",
      "cat": "reklam",
      "video": true,
      "videoSrc": "2funart-video13.mp4",
      "image": "assets/work/2funart-video13-poster.webp",
      "meta": "AI Karakter · Animasyon",
      "title": "The Kitchen Cat",
      "desc": "AI karakter geliştirme ve animasyon. Karakter tasarımı ve hareket tek elden."
    },
    {
      "id": "wolverine",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/Wolverine.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/Wolverine.webp",
        "assets/work/oyuncak-sektoru/wolverine/w2.webp",
        "assets/work/oyuncak-sektoru/wolverine/w3.webp",
        "assets/work/oyuncak-sektoru/wolverine/w4.webp",
        "assets/work/oyuncak-sektoru/wolverine/w5.webp",
        "assets/work/oyuncak-sektoru/wolverine/w6.webp",
        "assets/work/oyuncak-sektoru/wolverine/w7.webp",
        "assets/work/oyuncak-sektoru/wolverine/w8.webp",
        "assets/work/oyuncak-sektoru/wolverine/w9.webp",
        "assets/work/oyuncak-sektoru/wolverine/p1.webp",
        "assets/work/oyuncak-sektoru/wolverine/p2.webp"
      ],
      "meta": "Karakter · Figür",
      "title": "Wolverine",
      "desc": "Mondo 1/6 figürü; alternatif baş, el ve aksesuar setiyle çok açılı ürün galerisi."
    },
    {
      "id": "transistor",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/Transistor_RedFigurine_005.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/Transistor_RedFigurine_005.webp",
        "assets/work/oyuncak-sektoru/red/r1.webp",
        "assets/work/oyuncak-sektoru/red/r2.webp",
        "assets/work/oyuncak-sektoru/red/r3.webp",
        "assets/work/oyuncak-sektoru/red/r6.webp",
        "assets/work/oyuncak-sektoru/red/r7.webp",
        "assets/work/oyuncak-sektoru/red/slide.webp",
        "assets/work/oyuncak-sektoru/red/latest.webp",
        "assets/work/oyuncak-sektoru/red/c1.webp",
        "assets/work/oyuncak-sektoru/red/c2.webp",
        "assets/work/oyuncak-sektoru/red/c3.webp",
        "assets/work/oyuncak-sektoru/red/p1.webp",
        "assets/work/oyuncak-sektoru/red/p2.webp"
      ],
      "meta": "Karakter · Vinyl Figür",
      "title": "Transistor — Red",
      "desc": "Kutulu koleksiyon figürü ve ambalaj görseli; çok açılı detay galerisi."
    },
    {
      "id": "mlp",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/mlp-chibis.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/ponies/group.webp",
        "assets/work/oyuncak-sektoru/ponies/celestia.webp",
        "assets/work/oyuncak-sektoru/ponies/luna.webp",
        "assets/work/oyuncak-sektoru/ponies/fluttershy.webp",
        "assets/work/oyuncak-sektoru/ponies/rainbow.webp",
        "assets/work/oyuncak-sektoru/ponies/lyra.webp",
        "assets/work/oyuncak-sektoru/ponies/octavia.webp"
      ],
      "meta": "Karakter · Chibi Serisi",
      "title": "My Little Pony Chibis",
      "desc": "WeLoveFine chibi serisi; karakter ve grup lansman görselleri."
    },
    {
      "id": "mondoid",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/mondoid.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/mondoid.webp",
        "assets/work/oyuncak-sektoru/mondoids/melting-1.webp",
        "assets/work/oyuncak-sektoru/mondoids/melting-2.webp",
        "assets/work/oyuncak-sektoru/mondoids/melting-3.webp",
        "assets/work/oyuncak-sektoru/mondoids/raptor-1.webp",
        "assets/work/oyuncak-sektoru/mondoids/raptor-2.webp",
        "assets/work/oyuncak-sektoru/mondoids/trex-1.webp",
        "assets/work/oyuncak-sektoru/mondoids/trex-2.webp",
        "assets/work/oyuncak-sektoru/mondoids/melting-4.webp",
        "assets/work/oyuncak-sektoru/mondoids/vaultboy.webp",
        "assets/work/oyuncak-sektoru/mondoids/vaulthand.webp",
        "assets/work/oyuncak-sektoru/mondoids/gremlins.webp",
        "assets/work/oyuncak-sektoru/mondoids/caco-turn.webp",
        "assets/work/oyuncak-sektoru/mondoids/caco.webp",
        "assets/work/oyuncak-sektoru/mondoids/base.webp",
        "assets/work/oyuncak-sektoru/mondoids/mb1.webp",
        "assets/work/oyuncak-sektoru/mondoids/mb2.webp",
        "assets/work/oyuncak-sektoru/mondoids/r2293.webp",
        "assets/work/oyuncak-sektoru/mondoids/r2297.webp",
        "assets/work/oyuncak-sektoru/mondoids/key.webp",
        "assets/work/oyuncak-sektoru/mondoids/p1.webp",
        "assets/work/oyuncak-sektoru/mondoids/p2.webp",
        "assets/work/oyuncak-sektoru/mondoids/p3.webp",
        "assets/work/oyuncak-sektoru/mondoids/p4.webp",
        "assets/work/oyuncak-sektoru/mondoids/x1.webp",
        "assets/work/oyuncak-sektoru/mondoids/x2.webp",
        "assets/work/oyuncak-sektoru/mondoids/x3.webp",
        "assets/work/oyuncak-sektoru/mondoids/x4.webp",
        "assets/work/oyuncak-sektoru/mondoids/x5.webp",
        "assets/work/oyuncak-sektoru/mondoids/x6.webp",
        "assets/work/oyuncak-sektoru/mondoids/x7.webp",
        "assets/work/oyuncak-sektoru/mondoids/x8.webp",
        "assets/work/oyuncak-sektoru/mondoids/x9.webp",
        "assets/work/oyuncak-sektoru/mondoids/x10.webp",
        "assets/work/oyuncak-sektoru/mondoids/x11.webp",
        "assets/work/oyuncak-sektoru/mondoids/x12.webp",
        "assets/work/oyuncak-sektoru/mondoids/x13.webp",
        "assets/work/oyuncak-sektoru/mondoids/x14.webp",
        "assets/work/oyuncak-sektoru/mondoids/x15.webp",
        "assets/work/oyuncak-sektoru/mondoids/x16.webp",
        "assets/work/oyuncak-sektoru/mondoids/x17.webp",
        "assets/work/oyuncak-sektoru/mondoids/x18.webp",
        "assets/work/oyuncak-sektoru/mondoids/x19.webp",
        "assets/work/oyuncak-sektoru/mondoids/x20.webp",
        "assets/work/oyuncak-sektoru/mondoids/x21.webp",
        "assets/work/oyuncak-sektoru/mondoids/x22.webp",
        "assets/work/oyuncak-sektoru/mondoids/x23.webp",
        "assets/work/oyuncak-sektoru/mondoids/x24.webp",
        "assets/work/oyuncak-sektoru/mondoids/x25.webp",
        "assets/work/oyuncak-sektoru/mondoids/x26.webp",
        "assets/work/oyuncak-sektoru/mondoids/x27.webp"
      ],
      "meta": "Karakter · Vinyl Figür",
      "title": "Mondoids",
      "desc": "Materyal ve yüzey çalışması ön planda vinyl figür."
    },
    {
      "id": "abe",
      "cat": "karakter",
      "image": "assets/work/abe-sapien.webp",
      "gallery": [
        "assets/work/abe-poster.webp",
        "assets/work/abe-sapien.webp",
        "assets/work/oyuncak-sektoru/abe/abe-1.webp",
        "assets/work/oyuncak-sektoru/abe/abe-4.webp",
        "assets/work/oyuncak-sektoru/abe/abe-9.webp",
        "assets/work/oyuncak-sektoru/abe/abe-footer.webp",
        "assets/work/oyuncak-sektoru/abe/p1.webp",
        "assets/work/oyuncak-sektoru/abe/p2.webp",
        "assets/work/oyuncak-sektoru/abe/p3.webp",
        "assets/work/oyuncak-sektoru/abe/abe-front.webp",
        "assets/work/oyuncak-sektoru/abe/p4.webp",
        "assets/work/oyuncak-sektoru/abe/p5.webp",
        "assets/work/oyuncak-sektoru/abe/p6.webp",
        "assets/work/oyuncak-sektoru/abe/p7.webp",
        "assets/work/oyuncak-sektoru/abe/p8.webp",
        "assets/work/oyuncak-sektoru/abe/p9.webp",
        "assets/work/oyuncak-sektoru/abe/p10.webp",
        "assets/work/oyuncak-sektoru/abe/p11.webp",
        "assets/work/oyuncak-sektoru/abe/poster.webp"
      ],
      "meta": "Konsept · Karakter",
      "title": "Abe Sapien",
      "desc": "Konsept render, soğuk film-grade tamamlayıcı tonlar."
    },
    {
      "id": "gen2",
      "cat": "karakter",
      "image": "assets/work/shadowed-kingdom.webp",
      "gallery": [
        "assets/work/shadowed-kingdom.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk1.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk3.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk4.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk5.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk6.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk7.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk8.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk9.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk10.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk11.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk12.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk13.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk15.webp",
        "assets/work/oyuncak-sektoru/shadowed/sk16.webp",
        "assets/work/oyuncak-sektoru/shadowed/thumb.webp",
        "assets/work/oyuncak-sektoru/shadowed/gen-jqdxgv.webp",
        "assets/work/oyuncak-sektoru/shadowed/gen-jyzdsb.webp"
      ],
      "meta": "Tabletop Game Figür · Disney",
      "title": "The Shadowed Kingdom",
      "desc": "Disney karakterlerinden tabletop oyun figür serisi; konsept ve render galerisi."
    },
    {
      "id": "breezly",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/breezly-pop.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/pop/breezly.webp",
        "assets/work/oyuncak-sektoru/pop/topcat.webp",
        "assets/work/oyuncak-sektoru/pop/lippy-lion.webp",
        "assets/work/oyuncak-sektoru/pop/hardy-har-har.webp",
        "assets/work/oyuncak-sektoru/pop/metallica-james.webp",
        "assets/work/oyuncak-sektoru/pop/metallica-lars.webp",
        "assets/work/oyuncak-sektoru/pop/metallica-kirk.webp",
        "assets/work/oyuncak-sektoru/pop/metallica-robert.webp",
        "assets/work/oyuncak-sektoru/pop/elf-buddy.webp",
        "assets/work/oyuncak-sektoru/pop/elf-jovie.webp",
        "assets/work/oyuncak-sektoru/pop/elf-papa.webp",
        "assets/work/oyuncak-sektoru/pop/horror-norman.webp",
        "assets/work/oyuncak-sektoru/pop/horror-annabelle.webp",
        "assets/work/oyuncak-sektoru/pop/blackhole-maximillian.webp",
        "assets/work/oyuncak-sektoru/pop/blackhole-vincent.webp",
        "assets/work/oyuncak-sektoru/pop/figment.webp",
        "assets/work/oyuncak-sektoru/pop/wedge-antilles.webp",
        "assets/work/oyuncak-sektoru/pop/zack-ryder.webp",
        "assets/work/oyuncak-sektoru/pop/pop-extra1.webp",
        "assets/work/oyuncak-sektoru/pop/pop-extra2.webp",
        "assets/work/oyuncak-sektoru/pop/predator-pop.webp"
      ],
      "meta": "Funko · Vinyl Figür",
      "title": "Pop!",
      "desc": "Kutulu vinyl figür ve ambalaj görseli; stüdyo ışığıyla ürün çekimi. Seri galerisi."
    },
    {
      "id": "thundercats-diorama",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/funko-thundercats.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/funko-thundercats.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-1.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-2.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-3.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-4.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-5.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-6.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-7.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-8.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-9.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-10.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-11.webp",
        "assets/work/oyuncak-sektoru/thundercats/tc-12.webp",
        "assets/work/oyuncak-sektoru/thundercats/p1.webp",
        "assets/work/oyuncak-sektoru/thundercats/p2.webp",
        "assets/work/oyuncak-sektoru/thundercats/p3.webp",
        "assets/work/oyuncak-sektoru/thundercats/p4.webp",
        "assets/work/oyuncak-sektoru/thundercats/p5.webp",
        "assets/work/oyuncak-sektoru/thundercats/p6.webp",
        "assets/work/oyuncak-sektoru/thundercats/p7.webp",
        "assets/work/oyuncak-sektoru/thundercats/p8.webp",
        "assets/work/oyuncak-sektoru/thundercats/p9.webp",
        "assets/work/oyuncak-sektoru/thundercats/p10.webp",
        "assets/work/oyuncak-sektoru/thundercats/p11.webp",
        "assets/work/oyuncak-sektoru/thundercats/p12.webp"
      ],
      "meta": "Figür · Diorama",
      "title": "ThunderCats — Diorama",
      "desc": "Seri lansman görseli, sahne dioraması ve kompozisyon."
    },
    {
      "id": "nbc",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/dotakin/main.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/dotakin/main.webp",
        "assets/work/oyuncak-sektoru/dotakin/group.webp",
        "assets/work/oyuncak-sektoru/dotakin/s1.webp",
        "assets/work/oyuncak-sektoru/dotakin/s3.webp",
        "assets/work/oyuncak-sektoru/dotakin/p1.webp",
        "assets/work/oyuncak-sektoru/dotakin/p2.webp",
        "assets/work/oyuncak-sektoru/dotakin/p3.webp",
        "assets/work/oyuncak-sektoru/dotakin/p4.webp",
        "assets/work/oyuncak-sektoru/dotakin/p5.webp",
        "assets/work/oyuncak-sektoru/dotakin/p6.webp",
        "assets/work/oyuncak-sektoru/dotakin/p7.webp",
        "assets/work/oyuncak-sektoru/dotakin/p8.webp",
        "assets/work/oyuncak-sektoru/dotakin/p9.webp",
        "assets/work/oyuncak-sektoru/dotakin/p10.webp",
        "assets/work/oyuncak-sektoru/dotakin/p11.webp",
        "assets/work/oyuncak-sektoru/dotakin/p12.webp",
        "assets/work/oyuncak-sektoru/dotakin/p13.webp",
        "assets/work/oyuncak-sektoru/dotakin/p14.webp",
        "assets/work/oyuncak-sektoru/dotakin/p15.webp"
      ],
      "meta": "Figür · Seri",
      "title": "Dotakin",
      "desc": "Dotakins Series 2 blind-box serisi; karakter seti ve ambalaj galerisi."
    },
    {
      "id": "chibi-villain",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/nightmare/nbc-thumb.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/nightmare/nbc-group.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-behemoth.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-mayor.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-zero.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-jack.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-finkelstein.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-extra1.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-s1.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-s2.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-s3.webp",
        "assets/work/oyuncak-sektoru/nightmare/p1.webp",
        "assets/work/oyuncak-sektoru/nightmare/p2.webp",
        "assets/work/oyuncak-sektoru/nightmare/p3.webp",
        "assets/work/oyuncak-sektoru/nightmare/p4.webp",
        "assets/work/oyuncak-sektoru/nightmare/p5.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-group2.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-render.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-thumb.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-w1.webp",
        "assets/work/oyuncak-sektoru/nightmare/nbc-w2.webp"
      ],
      "meta": "Figür · Seri",
      "title": "Nightmare Before Christmas",
      "desc": "Tim Burton evreninden karakter seti; tutarlı palet ve yüzey çalışması."
    },
    {
      "id": "dragon",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/dragon/dragon-thumb.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/dragon/d1.webp",
        "assets/work/oyuncak-sektoru/dragon/d4.webp",
        "assets/work/oyuncak-sektoru/dragon/d5.webp",
        "assets/work/oyuncak-sektoru/dragon/d7.webp",
        "assets/work/oyuncak-sektoru/dragon/d8.webp",
        "assets/work/oyuncak-sektoru/dragon/d9.webp",
        "assets/work/oyuncak-sektoru/dragon/d12.webp",
        "assets/work/oyuncak-sektoru/dragon/d16.webp",
        "assets/work/oyuncak-sektoru/dragon/d17.webp",
        "assets/work/oyuncak-sektoru/dragon/d19.webp",
        "assets/work/oyuncak-sektoru/dragon/d3d.webp",
        "assets/work/oyuncak-sektoru/dragon/hero.webp",
        "assets/work/oyuncak-sektoru/dragon/p1.webp",
        "assets/work/oyuncak-sektoru/dragon/p2.webp",
        "assets/work/oyuncak-sektoru/dragon/p3.webp",
        "assets/work/oyuncak-sektoru/dragon/dragon-thumb.webp",
        "assets/work/oyuncak-sektoru/dragon/p4.webp",
        "assets/work/oyuncak-sektoru/dragon/p5.webp",
        "assets/work/oyuncak-sektoru/dragon/p6.webp",
        "assets/work/oyuncak-sektoru/dragon/p7.webp"
      ],
      "meta": "Figür · Heykel",
      "title": "Ice Dragon — Dark Horse",
      "desc": "Game of Thrones buz ejderhası heykeli; çok açılı detay galerisi."
    },
    {
      "id": "harley",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/harley/h1.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/harley/h1.webp",
        "assets/work/oyuncak-sektoru/harley/h2.webp",
        "assets/work/oyuncak-sektoru/harley/h3.webp",
        "assets/work/oyuncak-sektoru/harley/h4.webp",
        "assets/work/oyuncak-sektoru/harley/h5.webp",
        "assets/work/oyuncak-sektoru/harley/h6.webp",
        "assets/work/oyuncak-sektoru/harley/h7.webp",
        "assets/work/oyuncak-sektoru/harley/h8.webp",
        "assets/work/oyuncak-sektoru/harley/h9.webp",
        "assets/work/oyuncak-sektoru/harley/h10.webp",
        "assets/work/oyuncak-sektoru/harley/h11.webp",
        "assets/work/oyuncak-sektoru/harley/harley-thumb.webp"
      ],
      "meta": "Figür · Art Figür",
      "title": "Harley Quinn — Art Figür",
      "desc": "Kidrobot art figürü; renk ve poz detay galerisi."
    },
    {
      "id": "gorillaz",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/gorillaz/front.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/gorillaz/front.webp",
        "assets/work/oyuncak-sektoru/gorillaz/murdoc.webp",
        "assets/work/oyuncak-sektoru/gorillaz/noodle-head.webp",
        "assets/work/oyuncak-sektoru/gorillaz/noodle1.webp",
        "assets/work/oyuncak-sektoru/gorillaz/noodle2.webp",
        "assets/work/oyuncak-sektoru/gorillaz/wip1.webp",
        "assets/work/oyuncak-sektoru/gorillaz/wip2.webp",
        "assets/work/oyuncak-sektoru/gorillaz/wip3.webp",
        "assets/work/oyuncak-sektoru/gorillaz/wip4.webp"
      ],
      "meta": "Karakter · Figür",
      "title": "Gorillaz",
      "desc": "Gorillaz grup figürleri; karakter sculpt ve turnaround çalışmaları."
    },
    {
      "id": "jp",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/jp/b2.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/jp/b2.webp",
        "assets/work/oyuncak-sektoru/jp/scene.webp",
        "assets/work/oyuncak-sektoru/jp/arnold.webp",
        "assets/work/oyuncak-sektoru/jp/worker.webp",
        "assets/work/oyuncak-sektoru/jp/b.webp",
        "assets/work/oyuncak-sektoru/jp/untitled.webp",
        "assets/work/oyuncak-sektoru/jp/p1.webp",
        "assets/work/oyuncak-sektoru/jp/p2.webp",
        "assets/work/oyuncak-sektoru/jp/p3.webp",
        "assets/work/oyuncak-sektoru/jp/p4.webp",
        "assets/work/oyuncak-sektoru/jp/p5.webp",
        "assets/work/oyuncak-sektoru/jp/p6.webp",
        "assets/work/oyuncak-sektoru/jp/p7.webp",
        "assets/work/oyuncak-sektoru/jp/p8.webp",
        "assets/work/oyuncak-sektoru/jp/p9.webp",
        "assets/work/oyuncak-sektoru/jp/p10.webp",
        "assets/work/oyuncak-sektoru/jp/p11.webp",
        "assets/work/oyuncak-sektoru/jp/p12.webp",
        "assets/work/oyuncak-sektoru/jp/p13.webp",
        "assets/work/oyuncak-sektoru/jp/p14.webp",
        "assets/work/oyuncak-sektoru/jp/p15.webp",
        "assets/work/oyuncak-sektoru/jp/p16.webp",
        "assets/work/oyuncak-sektoru/jp/p17.webp",
        "assets/work/oyuncak-sektoru/jp/p18.webp",
        "assets/work/oyuncak-sektoru/jp/p19.webp",
        "assets/work/oyuncak-sektoru/jp/p20.webp",
        "assets/work/oyuncak-sektoru/jp/p21.webp",
        "assets/work/oyuncak-sektoru/jp/p22.webp"
      ],
      "meta": "Mondo Games · Minyatür",
      "title": "Jurassic Park — Unmatched",
      "desc": "Unmatched: Jurassic Park masa oyunu minyatürleri; karakter ve T-Rex sculpt çalışmaları."
    },
    {
      "id": "avatar",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/avatar/zuko.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/avatar/zuko.webp",
        "assets/work/oyuncak-sektoru/avatar/katara.webp",
        "assets/work/oyuncak-sektoru/avatar/aang.webp",
        "assets/work/oyuncak-sektoru/avatar/zuko2.webp",
        "assets/work/oyuncak-sektoru/avatar/zuko3.webp",
        "assets/work/oyuncak-sektoru/avatar/katara2.webp",
        "assets/work/oyuncak-sektoru/avatar/katara-bw.webp",
        "assets/work/oyuncak-sektoru/avatar/g1.webp",
        "assets/work/oyuncak-sektoru/avatar/g2.webp",
        "assets/work/oyuncak-sektoru/avatar/g3.webp",
        "assets/work/oyuncak-sektoru/avatar/g4.webp",
        "assets/work/oyuncak-sektoru/avatar/g5.webp",
        "assets/work/oyuncak-sektoru/avatar/katara-s1.webp",
        "assets/work/oyuncak-sektoru/avatar/katara-s2.webp",
        "assets/work/oyuncak-sektoru/avatar/katara3.webp",
        "assets/work/oyuncak-sektoru/avatar/korra-env.webp",
        "assets/work/oyuncak-sektoru/avatar/korra1.webp",
        "assets/work/oyuncak-sektoru/avatar/korra2.webp",
        "assets/work/oyuncak-sektoru/avatar/korra3.webp",
        "assets/work/oyuncak-sektoru/avatar/korra4.webp",
        "assets/work/oyuncak-sektoru/avatar/korra5.webp",
        "assets/work/oyuncak-sektoru/avatar/korra6.webp",
        "assets/work/oyuncak-sektoru/avatar/korra7.webp",
        "assets/work/oyuncak-sektoru/avatar/p1.webp",
        "assets/work/oyuncak-sektoru/avatar/p2.webp",
        "assets/work/oyuncak-sektoru/avatar/p3.webp",
        "assets/work/oyuncak-sektoru/avatar/p4.webp",
        "assets/work/oyuncak-sektoru/avatar/p5.webp",
        "assets/work/oyuncak-sektoru/avatar/p6.webp",
        "assets/work/oyuncak-sektoru/avatar/zuko-s1.webp",
        "assets/work/oyuncak-sektoru/avatar/zuko-s2.webp",
        "assets/work/oyuncak-sektoru/avatar/zuko-s3.webp",
        "assets/work/oyuncak-sektoru/avatar/zuko-s4.webp",
        "assets/work/oyuncak-sektoru/avatar/zuko-s5.webp"
      ],
      "meta": "Karakter · Figür",
      "title": "Avatar: Son Hava Bükücü",
      "desc": "Zuko, Katara ve Aang figürleri; ateş bükme efektiyle çok açılı turnaround."
    },
    {
      "id": "simpsons",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/simpsons/homer.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/simpsons/homer.webp",
        "assets/work/oyuncak-sektoru/simpsons/marge.webp",
        "assets/work/oyuncak-sektoru/simpsons/devil-flanders.webp",
        "assets/work/oyuncak-sektoru/simpsons/alien-president.webp",
        "assets/work/oyuncak-sektoru/simpsons/radioactive-man.webp",
        "assets/work/oyuncak-sektoru/simpsons/moomoo-homer.webp",
        "assets/work/oyuncak-sektoru/simpsons/drederick.webp",
        "assets/work/oyuncak-sektoru/simpsons/mcbain-commando.webp",
        "assets/work/oyuncak-sektoru/simpsons/mcbain-cop.webp",
        "assets/work/oyuncak-sektoru/simpsons/chef.webp",
        "assets/work/oyuncak-sektoru/simpsons/skowie.webp",
        "assets/work/oyuncak-sektoru/simpsons/dna2.webp",
        "assets/work/oyuncak-sektoru/simpsons/billy-troy.webp",
        "assets/work/oyuncak-sektoru/simpsons/bunny-troy.webp",
        "assets/work/oyuncak-sektoru/simpsons/group.webp",
        "assets/work/oyuncak-sektoru/simpsons/jimmy-troy.webp",
        "assets/work/oyuncak-sektoru/simpsons/moomoo2.webp",
        "assets/work/oyuncak-sektoru/simpsons/prod1.webp",
        "assets/work/oyuncak-sektoru/simpsons/prod2.webp",
        "assets/work/oyuncak-sektoru/simpsons/prod3.webp",
        "assets/work/oyuncak-sektoru/simpsons/prod4.webp",
        "assets/work/oyuncak-sektoru/simpsons/s2023-1.webp",
        "assets/work/oyuncak-sektoru/simpsons/s2023-2.webp",
        "assets/work/oyuncak-sektoru/simpsons/s2023-3.webp",
        "assets/work/oyuncak-sektoru/simpsons/s2023-4.webp",
        "assets/work/oyuncak-sektoru/simpsons/s2023-5.webp",
        "assets/work/oyuncak-sektoru/simpsons/s2023-6.webp"
      ],
      "meta": "Karakter · Figür",
      "title": "The Simpsons — Korku Evi",
      "desc": "Treehouse of Horror temalı Simpsons figür serisi; renkli karakter tasarımları."
    },
    {
      "id": "dino",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/dino/c1.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/dino/c1.webp",
        "assets/work/oyuncak-sektoru/dino/c2.webp",
        "assets/work/oyuncak-sektoru/dino/c3.webp",
        "assets/work/oyuncak-sektoru/dino/d1.webp",
        "assets/work/oyuncak-sektoru/dino/d2.webp",
        "assets/work/oyuncak-sektoru/dino/d3.webp",
        "assets/work/oyuncak-sektoru/dino/s1.webp"
      ],
      "meta": "A.İ · 3D Baskı",
      "title": "Dino",
      "desc": "Stilize dino figürü; A.İ konsept ve resin baskı çalışması."
    },
    {
      "id": "vale",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/vale/v1.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/vale/v1.webp",
        "assets/work/oyuncak-sektoru/vale/v2.webp",
        "assets/work/oyuncak-sektoru/vale/v3.webp",
        "assets/work/oyuncak-sektoru/vale/p1.webp",
        "assets/work/oyuncak-sektoru/vale/p2.webp",
        "assets/work/oyuncak-sektoru/vale/val-medusa.webp",
        "assets/work/oyuncak-sektoru/vale/val-mimic.webp"
      ],
      "meta": "Karakter · Figür",
      "title": "Vale — Barbar",
      "desc": "Barbar savaşçı figürü; konsept ve ürün görselleri."
    },
    {
      "id": "r3",
      "cat": "diger",
      "image": "assets/work/r3-3868.webp",
      "meta": "Ürün · Görsel",
      "title": "Ürün Çekimi",
      "desc": "Stüdyo zemininde ürün görseli."
    },
    {
      "id": "anit-heykel",
      "cat": "diger",
      "image": "assets/work/diger-isler/install2.webp",
      "gallery": [
        "assets/work/diger-isler/install2.webp",
        "assets/work/diger-isler/s-fig1.webp",
        "assets/work/diger-isler/s-fig2.webp",
        "assets/work/diger-isler/s-fig3.webp",
        "assets/work/diger-isler/r3.webp",
        "assets/work/diger-isler/s-horse1.webp",
        "assets/work/diger-isler/s-horse2.webp",
        "assets/work/diger-isler/s-horse3.webp",
        "assets/work/diger-isler/s-horse4.webp",
        "assets/work/diger-isler/s-horse5.webp",
        "assets/work/diger-isler/s-horse6.webp",
        "assets/work/diger-isler/r2.webp",
        "assets/work/diger-isler/install3.webp",
        "assets/work/diger-isler/install4.webp",
        "assets/work/diger-isler/r1.webp",
        "assets/work/diger-isler/r4.webp",
        "assets/work/diger-isler/r5.webp",
        "assets/work/diger-isler/install1.webp",
        "assets/work/diger-isler/02.webp"
      ],
      "meta": "Kamusal · Heykel & Anıt",
      "title": "Anıtsal Heykel Çalışmaları",
      "desc": "Kamusal anıt heykeller — klasik savaşçı, atlı figür ve zafer quadriga'sı; ZBrush sculpt'tan döküm ve montaja."
    },
    {
      "id": "w8",
      "cat": "diger",
      "image": "assets/work/oyuncak-sektoru/mugs/predator.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/mugs/serpent.webp",
        "assets/work/oyuncak-sektoru/mugs/predator.webp",
        "assets/work/oyuncak-sektoru/mugs/mickey.webp",
        "assets/work/oyuncak-sektoru/mugs/modok.webp",
        "assets/work/oyuncak-sektoru/mugs/scrooge.webp",
        "assets/work/oyuncak-sektoru/mugs/r7268.webp",
        "assets/work/oyuncak-sektoru/mugs/r3201.webp",
        "assets/work/oyuncak-sektoru/mugs/r1982.webp",
        "assets/work/oyuncak-sektoru/mugs/m8.webp",
        "assets/work/oyuncak-sektoru/mugs/m11.webp",
        "assets/work/oyuncak-sektoru/mugs/m12.webp",
        "assets/work/oyuncak-sektoru/mugs/m14.webp",
        "assets/work/oyuncak-sektoru/mugs/ariel.webp",
        "assets/work/oyuncak-sektoru/mugs/mikem.webp",
        "assets/work/oyuncak-sektoru/mugs/predator-turn.webp",
        "assets/work/oyuncak-sektoru/mugs/rev.webp",
        "assets/work/oyuncak-sektoru/mugs/spf.webp",
        "assets/work/oyuncak-sektoru/mugs/img6563.webp",
        "assets/work/oyuncak-sektoru/mugs/img6662.webp",
        "assets/work/oyuncak-sektoru/mugs/r3868b.webp",
        "assets/work/oyuncak-sektoru/mugs/g1.webp",
        "assets/work/oyuncak-sektoru/mugs/g2.webp",
        "assets/work/oyuncak-sektoru/mugs/g3.webp",
        "assets/work/oyuncak-sektoru/mugs/g4.webp",
        "assets/work/oyuncak-sektoru/mugs/g5.webp",
        "assets/work/oyuncak-sektoru/mugs/g6.webp",
        "assets/work/oyuncak-sektoru/mugs/g7.webp",
        "assets/work/oyuncak-sektoru/mugs/g8.webp",
        "assets/work/oyuncak-sektoru/mugs/g9.webp",
        "assets/work/oyuncak-sektoru/mugs/g10.webp",
        "assets/work/oyuncak-sektoru/mugs/g11.webp",
        "assets/work/oyuncak-sektoru/mugs/g12.webp",
        "assets/work/oyuncak-sektoru/mugs/g13.webp",
        "assets/work/oyuncak-sektoru/mugs/g14.webp",
        "assets/work/oyuncak-sektoru/mugs/g15.webp",
        "assets/work/oyuncak-sektoru/mugs/g16.webp",
        "assets/work/oyuncak-sektoru/mugs/g17.webp",
        "assets/work/oyuncak-sektoru/mugs/g18.webp",
        "assets/work/oyuncak-sektoru/mugs/g19.webp",
        "assets/work/oyuncak-sektoru/mugs/g20.webp",
        "assets/work/oyuncak-sektoru/mugs/g21.webp",
        "assets/work/oyuncak-sektoru/mugs/g22.webp",
        "assets/work/oyuncak-sektoru/mugs/g23.webp",
        "assets/work/oyuncak-sektoru/mugs/g24.webp",
        "assets/work/oyuncak-sektoru/mugs/g25.webp",
        "assets/work/oyuncak-sektoru/mugs/g26.webp",
        "assets/work/oyuncak-sektoru/mugs/g27.webp",
        "assets/work/oyuncak-sektoru/mugs/g28.webp",
        "assets/work/oyuncak-sektoru/mugs/g29.webp",
        "assets/work/oyuncak-sektoru/mugs/g30.webp",
        "assets/work/oyuncak-sektoru/mugs/g31.webp",
        "assets/work/oyuncak-sektoru/mugs/g32.webp",
        "assets/work/oyuncak-sektoru/mugs/g33.webp",
        "assets/work/oyuncak-sektoru/mugs/g34.webp",
        "assets/work/oyuncak-sektoru/mugs/g35.webp"
      ],
      "meta": "Ceramics · Mugs",
      "title": "Tiki Mugs",
      "desc": "Seramik tiki mug koleksiyonu; tasarım, turnaround ve üretim görselleri."
    },
    {
      "id": "img2411",
      "cat": "karakter",
      "image": "assets/work/oyuncak-sektoru/rickmorti/rm-1.webp",
      "gallery": [
        "assets/work/oyuncak-sektoru/rickmorti/rm-1.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-2.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-3.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-4.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-5.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-6.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-7.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-8.webp",
        "assets/work/oyuncak-sektoru/rickmorti/rm-9.webp"
      ],
      "meta": "Mondo · Heykel",
      "title": "Rick&Morti",
      "desc": "Mondo özel heykeli; turntable render seçkisi ve stüdyo ürün çekimi."
    }
  ],
  "quotes": [
    {
      "name": "Mike Bonanno",
      "role": "Transmission Toy Maker // Co-Founder Mondo // Ex-Creative Director",
      "text": "Teslim hızı ve revizyon süreci kusursuzdu. Brief'i tek seferde yakaladı, sonuç beklentimizin çok üstündeydi."
    },
    {
      "name": "Mert Çelik",
      "role": "Karakter Tasarımı",
      "text": "Karakterin yüz ifadeleri tam istediğimiz gibiydi. Pipeline'ı kendi kuruyor olması süreci inanılmaz hızlandırdı."
    },
    {
      "name": "Guillaume Paoletti",
      "role": "Ex Videorama Animation Project",
      "text": "Konsepten teslimat videosuna kadar her şeyi tek elden çözdü. İletişim net, sonuç sinematik."
    }
  ],
  "tools": [
    "ComfyUI",
    "LTX Video 2.3",
    "Flux 2",
    "Qwen Image Edit",
    "Z-Image Turbo",
    "ZBrush",
    "Custom Node Dev",
    "Lip-Sync Pipeline"
  ],
  "filters": [
    ["reklam","Reklam Filmleri+A.İ"],
    ["karakter","Figür Oyuncak Sektörü"],
    ["diger","Diğer İşler"],
    ["all","Tümü"]
  ],
  "i18n": {
    "en": {
      "filters": [
        ["reklam","AI Film Works"],
        ["karakter","Figure & Toy Industry"],
        ["diger","Other Works"],
        ["all","All"]
      ],
      "quotes": [
        { "name": "Mike Bonanno", "role": "Transmission Toy Maker // Co-Founder Mondo // Ex-Creative Director", "text": "Delivery speed and revision process were flawless. Nailed the brief on the first try — the result far exceeded our expectations." },
        { "name": "Mert Çelik", "role": "Character Design", "text": "The character's facial expressions were exactly what we wanted. Building his own pipeline made the whole process incredibly fast." },
        { "name": "Guillaume Paoletti", "role": "Ex Videorama Animation Project", "text": "Handled everything from concept to final delivery in-house. Clear communication, cinematic result." }
      ],
      "works": {
        "limo":               { "title": "Stray Dog Limo",                     "meta": "Ad · LTX 2.3 · 25fps",             "desc": "Rescued from the shelter." },
        "benzin":             { "title": "Gas Station — Animated Short",        "meta": "Clip · LTX 2.3 · 24fps",           "desc": "Two-character cinematic short with locked camera. Full pipeline from character design to lip-sync." },
        "kidrobot":           { "title": "Dog — Character Ad",                  "meta": "Ad · LTX 2.3 · 24fps",             "desc": "Short commercial with dog character. Lip-sync and animation full pipeline." },
        "donald":             { "title": "BunnySkate — Commercial",             "meta": "Ad · LTX 2.3 · 24fps",             "desc": "Skateboarding character commercial. Motion and scene lighting end-to-end AI pipeline." },
        "keyblade":           { "title": "Nesquik — Product Ad",                "meta": "Ad · LTX 2.3 · 24fps",             "desc": "Cinematic short for brand product campaign. Character and product edit in-house." },
        "toys":               { "title": "ToyS — Collectible Figure Ad",        "meta": "Ad · LTX 2.3 · 24fps",             "desc": "Cinematic product film for premium collectible figure. Scene lighting and materials via AI pipeline." },
        "park-problem":       { "title": "Park Problem",                        "meta": "AI Character · Animation",         "desc": "AI character development and animation. End-to-end local pipeline from concept to render." },
        "doc-comodoturtle":   { "title": "Doc — Komodo Turtle",                 "meta": "AI Character · Animation",         "desc": "AI character development and animation. Character design and motion in-house." },
        "dino":               { "title": "Dino",                                "meta": "AI Character · Animation",         "desc": "AI character development and animation. End-to-end local pipeline from concept to render." },
        "crab":               { "title": "Crab",                                "meta": "AI Character · Animation",         "desc": "AI character development and animation. Character design and motion in-house." },
        "mission-mars":       { "title": "Mission Mars",                        "meta": "AI Character · Animation",         "desc": "AI character development and animation. End-to-end local pipeline from concept to render." },
        "soldier":            { "title": "Soldier",                             "meta": "AI Character · Animation",         "desc": "AI character development and animation. Character design and motion in-house." },
        "2funart-mice":       { "title": "Kitchen Mouse",                        "meta": "AI Character · Animation",         "desc": "AI character development and animation. End-to-end local pipeline from concept to render." },
        "2funart-video13":    { "title": "The Kitchen Cat",                      "meta": "AI Character · Animation",         "desc": "AI character development and animation. Character design and motion in-house." },
        "wolverine":          { "title": "Wolverine",                           "meta": "Character · Figure",               "desc": "Mondo 1/6 figure; multi-angle product gallery with alternate head, hands and accessories." },
        "transistor":         { "title": "Transistor — Red",                   "meta": "Character · Vinyl Figure",         "desc": "Boxed collectible figure and packaging artwork; multi-angle detail gallery." },
        "mlp":                { "title": "My Little Pony Chibis",              "meta": "Character · Chibi Series",         "desc": "WeLoveFine chibi series; character and group launch visuals." },
        "mondoid":            { "title": "Mondoids",                           "meta": "Character · Vinyl Figure",         "desc": "Vinyl figure with material and surface work in the foreground." },
        "abe":                { "title": "Abe Sapien",                         "meta": "Concept · Character",              "desc": "Concept render, cool film-grade complementary tones." },
        "gen2":               { "title": "The Shadowed Kingdom",               "meta": "Tabletop Game Figure · Disney",    "desc": "Disney character tabletop game figure series; concept and render gallery." },
        "breezly":            { "title": "Pop!",                               "meta": "Funko · Vinyl Figure",             "desc": "Boxed vinyl figure and packaging artwork; studio lighting product photography. Series gallery." },
        "thundercats-diorama":{ "title": "ThunderCats — Diorama",             "meta": "Figure · Diorama",                 "desc": "Series launch visual, scene diorama and composition." },
        "nbc":                { "title": "Dotakin",                            "meta": "Figure · Series",                  "desc": "Dotakins Series 2 blind-box series; character set and packaging gallery." },
        "chibi-villain":      { "title": "Nightmare Before Christmas",         "meta": "Figure · Series",                  "desc": "Character set from Tim Burton's universe; consistent palette and surface work." },
        "dragon":             { "title": "Ice Dragon — Dark Horse",            "meta": "Figure · Sculpture",               "desc": "Game of Thrones ice dragon sculpture; multi-angle detail gallery." },
        "harley":             { "title": "Harley Quinn — Art Figure",          "meta": "Figure · Art Figure",              "desc": "Kidrobot art figure; color and pose detail gallery." },
        "gorillaz":           { "title": "Gorillaz",                           "meta": "Character · Figure",               "desc": "Gorillaz group figures; character sculpt and turnaround work." },
        "jp":                 { "title": "Jurassic Park — Unmatched",          "meta": "Mondo Games · Miniature",          "desc": "Unmatched: Jurassic Park board game miniatures; character and T-Rex sculpt work." },
        "avatar":             { "title": "Avatar: The Last Airbender",         "meta": "Character · Figure",               "desc": "Zuko, Katara and Aang figures; multi-angle turnaround with firebending effect." },
        "simpsons":           { "title": "The Simpsons — Treehouse of Horror", "meta": "Character · Figure",               "desc": "Treehouse of Horror themed Simpsons figure series; colorful character designs." },
        "dino":               { "title": "Dino",                               "meta": "A.I · 3D Print",                   "desc": "Stylized dino figure; AI concept and resin print work." },
        "vale":               { "title": "Vale — Barbarian",                   "meta": "Character · Figure",               "desc": "Barbarian warrior figure; concept and product visuals." },
        "r3":                 { "title": "Product Shot",                       "meta": "Product · Photo",                  "desc": "Studio floor product visual." },
        "anit-heykel":        { "title": "Monumental Sculpture Works",         "meta": "Public · Sculpture & Monument",    "desc": "Public monument sculptures — classic warrior, equestrian figure and victory quadriga; ZBrush sculpt to casting and installation." },
        "w8":                 { "title": "Tiki Mugs",                          "meta": "Ceramics · Mugs",                  "desc": "Ceramic tiki mug collection; design, turnaround and production visuals." },
        "img2411":            { "title": "Rick & Morty",                       "meta": "Mondo · Sculpture",                "desc": "Mondo exclusive sculpture; turntable render selection and studio product photography." }
      }
    }
  }
};
